// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EmployeeManagement.Entities
{
    public partial class admin_Login
    {
        [Key]
        public int Login_Id { get; set; }
        [Required]
        [StringLength(50)]
        public string User_Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Password { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Deleted_Time_Stamp { get; set; }
    }
}