// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EmployeeManagement.Entities
{
    public partial class Employee_Details
    {
        [Key]
        public int Employee_Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Full_Name { get; set; }
        [Required]
        [StringLength(50)]
        public string User_Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [StringLength(50)]
        public string Department { get; set; }
        [Required]
        [StringLength(50)]
        public string Matricule { get; set; }
        [Required]
        [StringLength(100)]
        public string Address { get; set; }
        public long Phone_Number { get; set; }
        [Required]
        [StringLength(50)]
        public string Gender { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }
    }
}