// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EmployeeManagement.Entities
{
    public partial class file_Details
    {
        [Key]
        public int File_Id { get; set; }
        [Required]
        [StringLength(100)]
        public string File_Name { get; set; }
        [Required]
        public byte[] File_Content { get; set; }
       
        [StringLength(100)]
        public string File_Extension { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }
    }
}